name: build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'notebooks/**'
jobs:
  build-n-publish:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive 
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.7
    - name: Build a source tarball
      run: pip install poetry-dynamic-versioning && poetry install --no-dev && poetry build --format sdist
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: poetry config pypi-token.pypi ${{ secrets.pypi_token }} && poetry publish
